CREATE TABLE listings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_name TEXT NOT NULL,
    location TEXT NOT NULL,
    job_title TEXT NOT NULL,
    job_description TEXT NOT NULL,
    pay TEXT NOT NULL,
    required_skills TEXT NOT NULL,
    additional_skills TEXT NOT NULL,
    date_listed TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
);